name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
    paths:
      - 'requirements.txt'
      - 'artifacts/model_trainer/**'
      - 'app.py'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://kanayojustice:$HF_TOKEN@huggingface.co/spaces/kanayojustice/Deployment-slr-enp-HF main
