
name: Sync to Hugging Face Hub
on:
  push:
    branches: [Deployment-CI/CD-HF]   # <-- Now listens to your deployment branch

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add space https://kanayojustice:$HF_TOKEN@huggingface.co/spaces/kanayojustice/Deployment-slr-enp-HF
          git push --force space Deployment-CI/CD-HF:main